#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════════════
# HyprFlux — theme-switch.sh
# Switch the active HyprFlux colour theme.
#
# Usage:
#   theme-switch.sh toggle          Cycle dark → light → rose-pine → dark
#   theme-switch.sh select          Open Rofi theme picker
#   theme-switch.sh set <name>      Apply a named theme (e.g. "dark", "light")
#   theme-switch.sh current         Print the currently active theme name
#
# How it works:
#   1. Swaps the ~/.config/hyprflux/themes/active.conf symlink.
#   2. Reloads Hyprland (picks up new colours via source chain).
#   3. Restarts Waybar, Dunst, SwayNC with new palette.
#   4. Updates GTK/Qt settings to match.
#
# Dependencies: hyprctl, waybar, dunst, swaync, rofi-wayland
# ══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

readonly THEMES_DIR="${HOME}/.config/hyprflux/themes"
readonly ACTIVE_LINK="${THEMES_DIR}/active.conf"
readonly ROFI_CONFIG="${HOME}/.config/rofi/theme-selector.rasi"
readonly STATE_FILE="${HOME}/.local/share/hyprflux/cache/active-theme"

# Ordered cycle list for "toggle"
readonly -a THEME_CYCLE=( dark catppuccin-mocha rose-pine dracula nord gruvbox everforest light )

# ── Helpers ───────────────────────────────────────────────────────────────────
notify() {
    command -v notify-send &>/dev/null \
        && notify-send --app-name="HyprFlux" \
                       --icon="preferences-desktop-theme" \
                       "$1" "${2:-}"
}

die() {
    echo "theme-switch: error: $*" >&2
    notify "Theme Error" "$*"
    exit 1
}

# ── Get current theme name ────────────────────────────────────────────────────
get_current() {
    if [[ -L "$ACTIVE_LINK" ]]; then
        local target
        target="$(readlink "$ACTIVE_LINK")"
        basename "$target" .conf
    else
        echo "dark"
    fi
}

# ── Generate ~/.config/waybar/colors.css from the active theme ───────────────
generate_waybar_colors() {
    local name="$1"
    local theme_file="${THEMES_DIR}/${name}.conf"
    local colors_file="${HOME}/.config/waybar/colors.css"

    [[ -f "$theme_file" ]] || return 0

    # Count #@wb entries
    local wb_count
    wb_count=$(grep -c '^#@wb' "$theme_file" 2>/dev/null || echo 0)
    if [[ "$wb_count" -eq 0 ]]; then
        warn "Theme '${name}' has no #@wb color entries — waybar colors unchanged"
        return 0
    fi

    # Generate GTK @define-color format (works with GTK3 + GTK4).
    # CSS custom properties (--var / var()) are NOT supported in GTK3.
    # Each #@wb line format:  #@wb <name> <value>
    # Output format:          @define-color <name> <value>;
    {
        printf '/* HyprFlux — Waybar colors.css\n'
        printf '   Auto-generated by theme-switch.sh — do not edit manually.\n'
        printf '   Active theme: %s\n' "$name"
        printf '   GTK @define-color format (GTK3 + GTK4 compatible) */\n\n'
        grep '^#@wb' "$theme_file" | while IFS= read -r line; do
            local entry cname cvalue
            entry="${line#\#@wb}"
            # strip leading whitespace
            entry="${entry#"${entry%%[! ]*}"}"
            cname="${entry%% *}"
            cvalue="${entry#* }"
            cvalue="${cvalue#"${cvalue%%[! ]*}"}"
            [[ -z "$cname" || -z "$cvalue" ]] && continue
            printf '@define-color %s %s;\n' "$cname" "$cvalue"
        done
    } > "$colors_file"

    info "Waybar colors.css updated for theme: ${name}"
}

# ── Apply a theme by name ─────────────────────────────────────────────────────
apply_theme() {
    local name="$1"
    local theme_file="${THEMES_DIR}/${name}.conf"

    [[ -f "$theme_file" ]] || die "Theme not found: ${name} (${theme_file})"

    # Swap symlink atomically
    ln -sf "$theme_file" "$ACTIVE_LINK"

    # Persist active theme name
    mkdir -p "$(dirname "$STATE_FILE")"
    printf '%s\n' "$name" > "$STATE_FILE"

    # Generate waybar color variables for the new theme
    generate_waybar_colors "$name"

    # Reload Hyprland compositor (picks up new colours via source chain)
    hyprctl reload &>/dev/null || true

    # Restart Waybar
    if command -v waybar &>/dev/null; then
        pkill -x waybar 2>/dev/null || true
        sleep 0.3
        waybar &
        disown
    fi

    # Restart Dunst
    if command -v dunst &>/dev/null; then
        pkill -x dunst 2>/dev/null || true
        sleep 0.2
        dunst &
        disown
    fi

    # Reload SwayNC
    if command -v swaync &>/dev/null; then
        pkill -x swaync 2>/dev/null || true
        sleep 0.2
        swaync &
        disown
    fi

    # Apply GTK theme based on dark/light
    apply_gtk_theme "$name"

    notify "Theme Applied" "$(printf '%s' "${name^}")"
    echo "theme-switch: applied theme '${name}'"
}

# ── Update GTK settings to match theme variant ───────────────────────────────
apply_gtk_theme() {
    local name="$1"
    local gtk_scheme="prefer-dark"
    local gtk_theme="Adwaita-dark"

    if [[ "$name" == "light" ]]; then
        gtk_scheme="prefer-light"
        gtk_theme="Adwaita"
    fi

    # GTK 3
    if [[ -f "${HOME}/.config/gtk-3.0/settings.ini" ]]; then
        sed -i "s/gtk-application-prefer-dark-theme=.*/gtk-application-prefer-dark-theme=$(
            [[ "$name" == "light" ]] && echo 0 || echo 1
        )/" "${HOME}/.config/gtk-3.0/settings.ini" 2>/dev/null || true
    fi

    # GTK 4 via gsettings
    if command -v gsettings &>/dev/null; then
        gsettings set org.gnome.desktop.interface color-scheme "$gtk_scheme" 2>/dev/null || true
        gsettings set org.gnome.desktop.interface gtk-theme "$gtk_theme"     2>/dev/null || true
    fi

    # Notify GTK apps via dbus
    if command -v dbus-send &>/dev/null; then
        dbus-send --session --dest=org.freedesktop.portal.Desktop \
            /org/freedesktop/portal/desktop \
            org.freedesktop.portal.Settings.SettingChanged \
            string:org.gnome.desktop.interface \
            string:color-scheme \
            variant:string:"${gtk_scheme}" 2>/dev/null || true
    fi
}

# ── Cycle through THEME_CYCLE ─────────────────────────────────────────────────
toggle_theme() {
    local current
    current="$(get_current)"
    local next="dark"
    local found=false

    for i in "${!THEME_CYCLE[@]}"; do
        if [[ "${THEME_CYCLE[$i]}" == "$current" ]]; then
            local next_idx=$(( (i + 1) % ${#THEME_CYCLE[@]} ))
            next="${THEME_CYCLE[$next_idx]}"
            found=true
            break
        fi
    done

    [[ "$found" == "false" ]] && next="dark"
    apply_theme "$next"
}

# ── Rofi theme picker ─────────────────────────────────────────────────────────
select_theme() {
    local current
    current="$(get_current)"

    # Gather all available themes
    local themes=()
    while IFS= read -r -d '' f; do
        local tname
        tname="$(basename "$f" .conf)"
        [[ "$tname" == "active" ]] && continue
        themes+=("$tname")
    done < <(find "$THEMES_DIR" -maxdepth 1 -name '*.conf' ! -name 'active.conf' -print0 | sort -z)

    [[ ${#themes[@]} -eq 0 ]] && die "No theme files found in ${THEMES_DIR}"

    # Build Rofi input; mark current theme with a bullet
    local rofi_input=""
    local active_idx=0
    local idx=0
    for t in "${themes[@]}"; do
        local label=""
        if [[ "$t" == "$current" ]]; then
            label="  ${t}  (active)"
        else
            label="  ${t}"
        fi
        rofi_input+="${label}\n"
        [[ "$t" == "$current" ]] && active_idx=$idx
        (( idx++ )) || true
    done

    local chosen
    chosen=$(printf '%b' "$rofi_input" \
        | rofi -dmenu \
               -config "$ROFI_CONFIG" \
               -p "󰔎  Select Theme" \
               -no-custom \
               -active "$active_idx" \
               2>/dev/null || echo "")

    [[ -z "$chosen" ]] && exit 0

    # Extract just the theme name (strip icon and status suffix)
    local selected_name
    selected_name=$(printf '%s' "$chosen" | sed 's/^[[:space:]]*[^[:space:]]* //' | sed 's/  (active)$//')
    selected_name="${selected_name// /}"

    [[ -z "$selected_name" ]] && exit 0
    apply_theme "$selected_name"
}

# ── Entry point ───────────────────────────────────────────────────────────────
main() {
    # Ensure themes directory exists
    [[ -d "$THEMES_DIR" ]] || die "Themes directory not found: ${THEMES_DIR}"

    local action="${1:-toggle}"

    case "$action" in
        toggle)     toggle_theme ;;
        select)     select_theme ;;
        current)    get_current ;;
        set)
            [[ -z "${2:-}" ]] && die "Usage: theme-switch.sh set <name>"
            apply_theme "$2"
            ;;
        *)
            echo "Usage: theme-switch.sh [toggle|select|set <name>|current]" >&2
            exit 1
            ;;
    esac
}

main "$@"
