#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════════════
# HyprFlux — wallpaper.sh
# Wallpaper manager using hyprpaper IPC via hyprctl.
#
# Usage:
#   wallpaper.sh menu        Open Rofi wallpaper picker
#   wallpaper.sh random      Apply a random wallpaper
#   wallpaper.sh restore     Re-apply the last used wallpaper (called at login)
#   wallpaper.sh set <path>  Apply a specific wallpaper directly
#
# Dependencies: hyprpaper, hyprctl, rofi-wayland, imagemagick, libnotify
# ══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

readonly WALLPAPER_DIR="${HOME}/Pictures/Wallpapers"
readonly CACHE_DIR="${HOME}/.local/share/hyprflux/wallpaper-cache"
readonly STATE_FILE="${HOME}/.local/share/hyprflux/cache/last-wallpaper"
readonly HYPRPAPER_CONF="${HOME}/.config/hypr/hyprpaper.conf"

readonly THUMB_W=300
readonly THUMB_H=169

# ── Helpers ───────────────────────────────────────────────────────────────────
notify() {
    command -v notify-send &>/dev/null \
        && notify-send --app-name="HyprFlux" --icon="image-x-generic" "$1" "${2:-}"
}

die() { echo "wallpaper: error: $*" >&2; notify "Wallpaper Error" "$*"; exit 1; }

check_deps() {
    command -v hyprpaper &>/dev/null || die "hyprpaper is not installed"
    command -v hyprctl   &>/dev/null || die "hyprctl is not installed"
}

# ── Generate thumbnail ────────────────────────────────────────────────────────
generate_thumbnail() {
    local src="$1"
    local thumb="${CACHE_DIR}/$(basename "${src}").thumb.jpg"
    mkdir -p "$CACHE_DIR"
    if [[ ! -f "$thumb" ]] || [[ "$src" -nt "$thumb" ]]; then
        if command -v magick &>/dev/null; then
            magick "$src" -thumbnail "${THUMB_W}x${THUMB_H}^" \
                -gravity center -extent "${THUMB_W}x${THUMB_H}" \
                -strip -quality 80 "$thumb" 2>/dev/null || true
        elif command -v convert &>/dev/null; then
            convert "$src" -thumbnail "${THUMB_W}x${THUMB_H}^" \
                -gravity center -extent "${THUMB_W}x${THUMB_H}" \
                -strip -quality 80 "$thumb" 2>/dev/null || true
        fi
    fi
    printf '%s' "$thumb"
}

# ── Apply wallpaper via hyprpaper IPC (hyprctl hyprpaper) ─────────────────────
apply_wallpaper() {
    local wallpaper="$1"
    [[ -f "$wallpaper" ]] || die "File not found: $wallpaper"

    # Get connected monitor names from hyprctl
    local monitors=()
    if command -v hyprctl &>/dev/null; then
        while IFS= read -r mon; do
            [[ -n "$mon" ]] && monitors+=("$mon")
        done < <(hyprctl monitors -j 2>/dev/null \
            | python3 -c "
import json,sys
try:
    for m in json.load(sys.stdin):
        print(m['name'])
except Exception:
    pass
" 2>/dev/null)
    fi
    [[ ${#monitors[@]} -eq 0 ]] && monitors=("")

    # Ensure hyprpaper is running
    if ! pgrep -x hyprpaper &>/dev/null; then
        hyprpaper &
        sleep 0.8
    fi

    # ── Preload the wallpaper into hyprpaper via IPC ──────────────────────────
    hyprctl hyprpaper preload "$wallpaper" 2>/dev/null \
        || { sleep 0.5 && hyprctl hyprpaper preload "$wallpaper" 2>/dev/null || true; }

    # ── Set the wallpaper on each monitor ─────────────────────────────────────
    for mon in "${monitors[@]}"; do
        hyprctl hyprpaper wallpaper "${mon},${wallpaper}" 2>/dev/null || true
    done

    # ── Update hyprpaper.conf so it persists across restarts ─────────────────
    {
        printf '# HyprFlux — auto-generated by wallpaper.sh\n'
        printf '# Do not edit manually — use wallpaper.sh or Super+W\n\n'
        printf 'ipc     = on\n'
        printf 'splash  = false\n\n'
        printf 'preload = %s\n\n' "$wallpaper"
        for mon in "${monitors[@]}"; do
            printf 'wallpaper = %s,%s\n' "$mon" "$wallpaper"
        done
    } > "$HYPRPAPER_CONF"

    # ── Cache the selection ────────────────────────────────────────────────────
    mkdir -p "$(dirname "$STATE_FILE")"
    printf '%s\n' "$wallpaper" > "$STATE_FILE"

    notify "Wallpaper Applied" "$(basename "$wallpaper")"
}

# ── Rofi wallpaper picker ─────────────────────────────────────────────────────
open_menu() {
    [[ -d "$WALLPAPER_DIR" ]] || die "No wallpapers found. Add images to: ${WALLPAPER_DIR}"

    local images=()
    while IFS= read -r -d '' f; do
        images+=("$f")
    done < <(find "$WALLPAPER_DIR" -maxdepth 3 \
        \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \
           -o -iname '*.webp' \) -print0 2>/dev/null | sort -z)

    [[ ${#images[@]} -eq 0 ]] && die "No images found in ${WALLPAPER_DIR}"

    # Generate thumbnails (background, non-blocking)
    for img in "${images[@]}"; do generate_thumbnail "$img" &>/dev/null & done
    wait

    local current_wall=""
    [[ -f "$STATE_FILE" ]] && current_wall="$(cat "$STATE_FILE")"

    local rofi_input=""
    for img in "${images[@]}"; do
        local name thumb active=""
        name="$(basename "$img")"
        thumb="$(generate_thumbnail "$img")"
        [[ "$img" == "$current_wall" ]] && active="● "
        rofi_input+="${active}${name}\x00icon\x1f${thumb}\n"
    done

    local chosen
    chosen=$(printf '%b' "$rofi_input" \
        | rofi -dmenu \
               -config ~/.config/rofi/launcher.rasi \
               -p "󰸉  Wallpaper" \
               -i \
               -show-icons \
               -theme-str 'listview{columns:3;lines:3;}
                            element-icon{size:80px;}
                            window{width:860px;}' \
               2>/dev/null || true)

    [[ -z "$chosen" ]] && exit 0
    chosen="${chosen#● }"

    local selected=""
    for img in "${images[@]}"; do
        [[ "$(basename "$img")" == "$chosen" ]] && { selected="$img"; break; }
    done

    [[ -z "$selected" ]] && die "Could not resolve: $chosen"
    apply_wallpaper "$selected"
}

# ── Random wallpaper ──────────────────────────────────────────────────────────
random_wallpaper() {
    [[ -d "$WALLPAPER_DIR" ]] || die "Wallpaper directory not found: ${WALLPAPER_DIR}"

    local images=()
    while IFS= read -r -d '' f; do
        images+=("$f")
    done < <(find "$WALLPAPER_DIR" -maxdepth 3 \
        \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' \) \
        -print0 2>/dev/null)

    [[ ${#images[@]} -eq 0 ]] && die "No wallpapers found in ${WALLPAPER_DIR}"
    apply_wallpaper "${images[$(( RANDOM % ${#images[@]} ))]}"
}

# ── Restore last wallpaper (autostart) ───────────────────────────────────────
restore_wallpaper() {
    if [[ -f "$STATE_FILE" ]]; then
        local last
        last="$(cat "$STATE_FILE")"
        if [[ -f "$last" ]]; then
            apply_wallpaper "$last"
            return 0
        fi
    fi
    # No cache — pick random if wallpapers exist
    [[ -d "$WALLPAPER_DIR" ]] && random_wallpaper || true
}

# ── Entry point ───────────────────────────────────────────────────────────────
main() {
    check_deps
    case "${1:-menu}" in
        menu)    open_menu ;;
        random)  random_wallpaper ;;
        restore) restore_wallpaper ;;
        set)
            [[ -z "${2:-}" ]] && die "Usage: wallpaper.sh set <path>"
            apply_wallpaper "$2"
            ;;
        *)
            echo "Usage: wallpaper.sh [menu|random|restore|set <path>]" >&2
            exit 1
            ;;
    esac
}

main "$@"
